name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image and push to GitHub Packages
      run: |
        VERSION=$(date +%s)
        docker build ./services/sbus-queue-reader/ --file ./services/sbus-queue-reader/Dockerfile --tag docker.pkg.github.com/grizzljt/azdo-github-actions/sbus-reader:${VERSION}
        docker login docker.pkg.github.com --username grizzljt --password ${{ secrets.GITHUB_TOKEN }}
        docker push docker.pkg.github.com/grizzljt/azdo-github-actions/sbus-reader:${VERSION}