name: 'Terraform'

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform
        
    steps:
    # - name: Checkout
    #   uses: actions/checkout@v2

    # - name: Setup Terraform
    #   uses: hashicorp/setup-terraform@v1

    # - name: Terraform Init
    #   run: terraform init

    # - name: Terraform Format
    #   run: terraform fmt -check

    # - name: Terraform Plan
    #   run: terraform plan

    # - name: Terraform Apply
    #   if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    #   run: terraform apply -auto-approve



    - name: "Checkout"
      uses: actions/checkout@master

    - name: "Terraform Init"
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.28
        tf_actions_subcommand: 'init'
        tf_actions_working_dir: './terraform'
        args: '-var="client_secret=${{ secrets.clientSecret }}" -var="ARM_TENANT_ID=55a46e16-637a-4cfb-acaa-d89183887b16" -var="ARM_SUBSCRIPTION_ID=acd2e298-d61f-4ed2-8b28-dc2f60d9f382" -var="ARM_CLIENT_ID=02b6c340-bab3-472a-bb22-8d7241444b80" -var="ARM_CLIENT_SECRET=UTbbV.uyRXcmMk~VdymQDUCba3~74K6_52" -var="ARM_ACCESS_KEY=f/SQibk3XRJ/KSzc8k3sFcCDaNXNGzkRsKpAsMSEw4c/iLpjQgTkCFWMsfh9o4Ih2hWIrETk4ydqTdJmur9FZw=="'

    - name: "Terraform Plan"
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.28
        tf_actions_subcommand: "plan"
        args: '-v="client_secret=${{ secrets.clientSecret }} ARM_TENANT_ID=55a46e16-637a-4cfb-acaa-d89183887b16 ARM_SUBSCRIPTION_ID=acd2e298-d61f-4ed2-8b28-dc2f60d9f382 ARM_CLIENT_ID=02b6c340-bab3-472a-bb22-8d7241444b80 ARM_CLIENT_SECRET=UTbbV.uyRXcmMk~VdymQDUCba3~74K6_52 ARM_ACCESS_KEY=f/SQibk3XRJ/KSzc8k3sFcCDaNXNGzkRsKpAsMSEw4c/iLpjQgTkCFWMsfh9o4Ih2hWIrETk4ydqTdJmur9FZw=="'
    
    # - name: "Terraform Apply"
    #   uses: hashicorp/terraform-github-actions@master
    #   with:
    #     tf_actions_version: 0.12.28
    #     tf_actions_subcommand: "apply"
    #     args: '-var="client_secret=${{ secrets.clientSecret }}"'
