name: "Terraform Apply"

# Trigger when commits are pushed to the master branch
on:
  push:
    branches:
      - master

jobs:
  terraform-plan:
    name: "Terraform Apply"
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    # set the working direction to /terraform
    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      # Checkout the code
      # Marketplace: https://github.com/marketplace/actions/checkout
      - name: "Setup - Checkout"
        uses: actions/checkout@v2.1.0

      # Downloads a specific version of Terraform CLI and adds it to PATH
      # Marketplace: https://github.com/marketplace/actions/hashicorp-setup-terraform
      - name: "Setup - Terraform CLI"
        uses: hashicorp/setup-terraform@v1.1.0

      # Init pulls credentials from the .aws/credentials file by default
      - name: "Run - Terraform Init"
        run: terraform init -input=false -backend-config="access_key=${{ secrets.ACCESSKEY }}"

      # Auto-approve prevents the requirement of human interaction
      - name: "Run - Terraform Apply"
        run: terraform apply -input=false -var="client_secret=${{ secrets.clientSecret }} -auto-approve